# Copy this file to config/db.properties and set your MySQL password.
# Create database: CREATE DATABASE yebu_hotel CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
db.url=jdbc:mysql://yebu-tour.cj4g00um8uz4.eu-north-1.rds.amazonaws.com:3306/yebutour?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
db.user=admin
db.password=admin1234
image.cloudinary.cloud_name=dpnzf1ewi
image.cloudinary.upload_preset=yebu_tour_images